In [16]:
#one way to import 
# from tensorflow.keras.datasets import imdb
#anothor way to import 
from keras.datasets import imdb

In [17]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [18]:
train_data.shape

(25000,)

In [19]:
test_data.shape

(25000,)

In [20]:
train_labels

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [21]:
test_labels

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [22]:
max([max(sequence) for sequence in  train_data])

9999

In [23]:
train_data[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

So this is number, the actual data is a text review of movice, so it encoded here we will see the actual english review to decode the dataset

In [24]:
word_index = imdb.get_word_index()
reverse_word_index = dict(
    [(value, key) for (key, value) in word_index.items()])
decode_review = ' '.join(
    [reverse_word_index.get(i - 3, '?') for i in train_data[0]])

In [25]:
train_data[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

##  Encoding the integer sequences into a binary matrix

In [26]:
import numpy as np

In [28]:
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension)) #Creates an all-zero matrix of shape (len(sequences), dimension)
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1. #Sets specific indices of results[i] to 1s
    return results

In [29]:
x_train = vectorize_sequences(train_data) #Vectorized training data

In [30]:
x_test = vectorize_sequences(test_data) #Vectorized test data

In [32]:
x_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [33]:
x_test[1]

array([0., 1., 1., ..., 0., 0., 0.])

In [34]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [35]:
y_train[1]

0.0

In [36]:
y_test[1]

1.0

#### Now the data is ready to be fed into a neural network

# Building your network

output = relu(dot(W, input) + b)

In [37]:
from keras import models
from keras import layers

In [38]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

# Compiling the model

In [39]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

You’re passing your optimizer, loss function, and metrics as strings, which is possible
because rmsprop, binary_crossentropy, and accuracy are packaged as part of Keras.

### Configuring the optimizer
Some time we are doing custom loss function like

In [40]:
from keras import optimizers
model.compile(optimizer=optimizers.RMSprop(lr=0.001),
             loss='binary_crossentropy',
             metrics = ['accuracy'])

C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\rmsprop.py:143: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [41]:
from keras import losses
from keras import metrics
model.compile(optimizer=optimizers.RMSprop(lr=0.001),
loss=losses.binary_crossentropy,
metrics=[metrics.binary_accuracy])

#  Setting aside a validation set

In [42]:
x_val = x_train[:10000]
partial_x_train = x_train[10000:]

In [43]:
y_val = y_train[:10000]
partial_y_train = y_train[10000:]

#  Training your model

In [44]:
model.compile(optimizer = 'rmsprop',
             loss = 'binary_crossentropy',
             metrics=['acc'])

In [45]:
history = model.fit(partial_x_train,
                   partial_y_train,
                   epochs=20,
                   batch_size=512,
                   validation_data=(x_val,y_val))

Epoch 1/20
30/30 [==============================] - 40s 648ms/step - loss: 0.5049 - acc: 0.7839 - val_loss: 0.3798 - val_acc: 0.8704
Epoch 2/20
30/30 [==============================] - 1s 31ms/step - loss: 0.3057 - acc: 0.8994 - val_loss: 0.3031 - val_acc: 0.8865
Epoch 3/20
30/30 [==============================] - 1s 34ms/step - loss: 0.2324 - acc: 0.9222 - val_loss: 0.2804 - val_acc: 0.8907
Epoch 4/20
30/30 [==============================] - 1s 31ms/step - loss: 0.1883 - acc: 0.9373 - val_loss: 0.2940 - val_acc: 0.8807
Epoch 5/20
30/30 [==============================] - 1s 32ms/step - loss: 0.1594 - acc: 0.9465 - val_loss: 0.2785 - val_acc: 0.8881
Epoch 6/20
30/30 [==============================] - 1s 32ms/step - loss: 0.1359 - acc: 0.9561 - val_loss: 0.2879 - val_acc: 0.8839
Epoch 7/20
30/30 [==============================] - 1s 31ms/step - loss: 0.1191 - acc: 0.9630 - val_loss: 0.2974 - val_acc: 0.8825
Epoch 8/20
30/30 [==============================] - 1s 34ms/step - loss: 0.1001 -

In [46]:
history_dict= history.history

In [47]:
history_dict.keys()

dict_keys(['loss', 'acc', 'val_loss', 'val_acc'])

#  Plotting the training and validation loss

In [52]:
import matplotlib.pyplot as plt
history_dict = history.history
loss_values = history_dict['loss']
val_loss_values = history_dict['val_loss']
epochs = range(1, len(acc) + 1)
plt.plot(epochs, loss_values, 'bo', label='Training loss')
plt.plot(epochs, val_loss_values, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

NameError: name 'acc' is not defined

#  Plotting the training and validation accuracy

In [53]:
plt.clf()
acc_values = history_dict['acc']
val_acc_values = history_dict['val_acc']
plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

NameError: name 'acc' is not defined

<Figure size 640x480 with 0 Axes>

##### Let’s train a new network from scratch for four epochs and then evaluate it on the test data

In [65]:
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [66]:
model.compile(optimizer='rmsprop',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [67]:
model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test, y_test)

Epoch 1/4
49/49 [==============================] - 12s 42ms/step - loss: 0.4665 - accuracy: 0.8102
Epoch 2/4
49/49 [==============================] - 2s 47ms/step - loss: 0.2754 - accuracy: 0.9012
Epoch 3/4
49/49 [==============================] - 2s 34ms/step - loss: 0.2152 - accuracy: 0.9222
Epoch 4/4
782/782 [==============================] - 33s 5ms/step - loss: 0.2959 - accuracy: 0.8818


In [68]:
results

[0.2958913743495941, 0.8817600011825562]